1.0.0 proposal
Lauriethefish/QuestPatcher.QMod pull request #2
Opened 2022-03-27 19:19 UTC by Lauriethefish

Current changes:
- Allow omitting `packageId`, which indicates that the mod works for any package.

Please give any further ideas for schema changes for 1.0.0, bearing in mind that old mods need to still be compatible.

2022-03-27 20:36 UTC, sc2ad requested changes
I think this is a reasonable change, if you wish to continue on this track, you could potentially optionally omit `packageVersion` and expect the package to work on any version of any package (should certainly be omitted for cases where `packageId` is omitted anyways).

At the very least, specifying `packageVersion` as required is redundant if `packageId` is omitted, so that should be changed, imo.

2022-03-27 20:36 UTC, sc2ad commented on QuestPatcher.QMod/QModManifest.cs
>          {
In this file, consider resolving the potential null references to the `QModManifest` type before merging this featureset.

2022-03-28 05:19 UTC, Lauriethefish commented
`packageVersion` is now optional, even if `packageId` is specified.

2022-03-28 05:27 UTC, sc2ad commented on QuestPatcher.QMod/QModManifest.cs
> +        /// Specifying this is redundant if <see cref="PackageId"/> is specified.
What's the verbage meant to mean here? This makes it seem like specifying the `packageVersion` is redundant if the `packageId` is specified. Isn't it the opposite that is the case?

2022-03-28 05:28 UTC, sc2ad commented on QuestPatcher.QMod/QModManifest.cs
> +        /// Specifying this is redundant if <see cref="PackageId"/> is specified.
Perhaps using a word such as "omitting this is redundant..." or "specifying this is redundant... is not specified"

2022-03-28 05:28 UTC, sc2ad commented on QuestPatcher.QMod/Resources/qmod.schema.json
> +      "description": "The Android package version of the target package. If not specified, the mod does not depend on any particular package version. Specifying this is redundant if packageId is not
ditto previous

2022-03-28 05:28 UTC, sc2ad approved these changes
Overall approved

2022-03-31 09:57 UTC, merged